spring:
  output:
    ansi:
      enabled: DETECT
  profiles:
    active: default
  datasource:
    configuration:
      maximum-pool-size: 40
  main:
    allow-circular-references: true
    banner-mode: off
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    url: ${JDBC_DATABASE_URL}
    user: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    drop-first: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
      open-in-view: false
logging:
  level:
    liquibase: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

api:
  daily_domain:
    url: https://backorder.ru/json/?order=desc&expired=1&by=hotness&page=1&items=50
bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
